name: my workflow
on: [push]
jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "Install black"
        run: pip install black
      - name: "Run black"
        run: black --check .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "Install dependencies"
        run: pip install pytest coverage numpy matplotlib
      - name: "Pytest"
        run: python -m pytest
      - name: "Run coverage"
        run: coverage run -m
      - name: "Upload artefact"
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: .coverage
          retention-days: 5